### ISSUE TITLE
Host FREDSum on HF

### ISSUE THREAD

**Issue by NielsRogge** [linagora-labs/FREDSum#1]
Hi folks,

Would be great if you could host your dataset on the HF hub. Comes with a handy viewer, discussion tab, etc.

See this summarization dataset as an example: https://huggingface.co/datasets/samsum.

A guide is here: https://huggingface.co/docs/datasets/loading.

Thanks!

**Comment by Houpert** [comment]
Hello,

Thank you for your suggestion. While we appreciate your input, we currently don't have plans to make any changes to the database.

Best regards,

**Comment by damienlaine** [comment]
@Jeronymous : that's for you.

**Comment by VRennard** [comment]
Hey,

We are working on it ! 

Thank you !

**Comment by VRennard** [comment]
Hello !

Sorry for the delay, the dataset has been uploaded on huggingface at :

https://huggingface.co/datasets/linagora/FREDSum

Thank you !

**Comment by NielsRogge** [comment]
Awesome, thanks a lot! 🤗
